steps:
  # 1. Run Unit Tests
  - name: 'python:3.9-slim'
    id: 'unit-tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir -r requirements.txt pytest
        pytest test_app.py

  # 2. Security Linting & SAST
  - name: 'python:3.9-slim'
    id: 'security-scan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install bandit flake8
        bandit -r app.py -ll || true
        flake8 app.py --max-line-length=120 || true

  # 3. Build Container Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/flask-app:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/flask-app:latest'
      - '.'

  # 4. Push Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/flask-app:$SHORT_SHA'

  # 5. Deploy directly to DEV Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-dev'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'flask-app-dev'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/flask-app:$SHORT_SHA'
      - '--region=us-central1'
      - '--port=8080'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'
   # Step 6: Terraform Automate
  - name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform init
        terraform apply -lock=false -auto-approve


timeout: '1200s'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/flask-app:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/flask-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
